# SPDX-FileCopyrightText: 2026  Igalia S.L.
# SPDX-License-Identifier: MIT

import os
import subprocess

from pathlib import Path

from . import log, utils
from .config import ConfigSource
from .project import Project


HELP_MSG = "Build a Moonforge project"

HELP_DESCRIPTION = """The build command sets up a containerized environment to build the Moonforge project at the given PATH.

The container engine is defined by the 'container.engine' configuration key.

The container image is defined by the 'container.image_path', 'container.image_name', and 'container.image_version' configuration keys'.

The cached sstate directory is defined by the 'build.sstate_dir' configuration key.

The cached downloads directory is defined by the 'build.download_dir' configuration key.

The values of 'build.sstate_dir' and 'build.download_dir' can contain these placeholders:

- @XDG_CACHE_HOME@: expands to the XDG_CACHE_HOME environment variable
- @XDG_CONFIG_HOME@: expands to the XDG_CONFIG_HOME environment variable
- @HOME@: expands to the HOME environment variable
- @PROJECT_NAME@: expands to the project's name

The build artefacts are stored in the "build" directory.

Examples:

- Build the project in the current directory:

    moonforge build .

- Build the project in the Project/derivative directory:

    moonforge build Project/derivative

- Build the project in the current directory, with an additional fragment:

    moonforge build --fragment kas/common/debug.yml .
"""  # noqa: E501


def build_project(
    project: Project,
    source: ConfigSource,
    fragments: list[Path],
    runtime_args: str | None,
) -> int:
    log.info(f"Building project {project.name} at {project.path}")
    log.info(f"Machine: {project.machine.name}")
    features = ", ".join([f.name for f in project.features])
    log.info(f"Features: {features}")
    variables = ", ".join([x for x in project.variables])
    log.info(f"Variables: {variables}")
    log.info(f"Local repo name: {project.local_repo_name}")
    log.info(f"Container engine: {source['container.engine']}")

    kas_file = f"{project.name}-image-base-{project.machine.name}.yml"
    log.info(f"KAS file: {kas_file}")
    container_image = f"{source['container.image_path']}/{source['container.image_name']}:{source['container.image_version']}"
    log.info(f"KAS container image: {container_image}")
    sstate_dir = project.safe_path_replace(source["build.sstate_dir"])
    log.debug(f"SSTATE_DIR = {sstate_dir}")
    dl_dir = project.safe_path_replace(source["build.download_dir"])
    log.debug(f"DL_DIR = {dl_dir}")

    work_dir = os.getcwd()
    build_dir = Path(work_dir) / "build"
    try:
        build_dir.mkdir(parents=True, exist_ok=True)
        gitignore = build_dir / ".gitignore"
        with gitignore.open(mode="w") as f:
            f.write("# This file is autogenerated by moonforge; any change will be ignored when the directory is recreated.")
            f.write("*\n")
    except Exception as err:
        log.error(f"Unable to create build directory: {err}")

    try:
        sstate_dir.mkdir(parents=True, exist_ok=True)
        dl_dir.mkdir(parents=True, exist_ok=True)
    except Exception as err:
        log.error(f"Unable to create cache directories: {err}")

    engine = utils.find_program(source["container.engine"], error_if_not_found=True)
    assert engine is not None

    cmdline = [engine, "run"]

    cmdline.extend([
        "-v", f"{project.path}:/repo:ro",
        "-v", f"{work_dir}:/work:rw",
        "-v", f"{build_dir}:/build:rw",
        "-v", f"{dl_dir}:/downloads:rw",
        "-v", f"{sstate_dir}:/sstate:rw",
        "--workdir=/repo",
        "-e", "KAS_WORK_DIR=/work",
        "-e", "KAS_BUILD_DIR=/build",
        "-e", "DL_DIR=/downloads",
        "-e", "SSTATE_DIR=/sstate",
        "-e", f"USER_ID={os.getuid()}",
        "-e", f"GROUP_ID={os.getgid()}",
        "--rm",
        "--init",
    ])

    kas_env = {
        "TERM": os.environ.get("TERM"),
        "KAS_DISTRO": os.environ.get("KAS_DISTRO"),
        "KAS_MACHINE": os.environ.get("KAS_MACHINE"),
        "KAS_TARGET": os.environ.get("KAS_TARGET"),
        "KAS_TASK": os.environ.get("KAS_TASK"),
        "KAS_CLONE_DEPTH": os.environ.get("KAS_CLONE_DEPTH"),
        "KAS_PREMIRRORS": os.environ.get("KAS_PREMIRRORS"),
        "DISTRO_APT_PREMIRRORS": os.environ.get("DISTRO_APT_PREMIRRORS"),
        "BB_NUMBER_THREADS": os.environ.get("BB_NUMBER_THREADS"),
        "PARALLEL_MAKE": os.environ.get("PARALLEL_MAKE"),
        "GIT_CREDENTIAL_USEHTTPPATH": os.environ.get("GIT_CREDENTIAL_USEHTTPPATH"),
    }

    for var in kas_env:
        if kas_env[var] is not None:
            cmdline.append(f'-e {var}="{kas_env[var]}"')

    shell = os.environ.get("SHELL")
    match shell:
        case "/bin/sh" | "/bin/bash" | "/bin/dash":
            cmdline.append(f"-e SHELL={shell}")
        case _:
            cmdline.append("-e SHELL=/bin/bash")

    cmdline.extend([
        "--log-driver=none",
        "--user=root",
    ])

    if source["container.engine"] == "podman":
        cmdline.extend([
            "--security-opt", "label=disable",
            "--userns=keep-id",
        ])

    if runtime_args is not None:
        cmdline.append(runtime_args)

    cmdline.append(container_image)

    # All fragment paths are normalized and resolved to ensure that they
    # exist before creating the execution environment; now we have to
    # normalize them again against the volume exposed in the container
    project_basedir = project.path.name
    fragment_files = [str(Path("/repo/kas") / kas_file)]
    for kf in fragments:
        idx = kf.parts.index(project_basedir)
        fragment_files.append(str(Path("/repo").joinpath(*kf.parts[idx + 1:])))

    kas_files = ":".join(fragment_files)
    cmdline.extend(["build", kas_files])

    log.debug(f"cmdline: {' '.join(cmdline)}")

    try:
        proc = subprocess.run(cmdline)
    except Exception as err:
        log.error(f"Unable to build project: {err}")

    return proc.returncode


def add_args(parser):
    parser.add_argument("--fragment", metavar="FILE", dest="fragments",
                        action="append", default=[], help="additional kas fragments")
    parser.add_argument("--runtime-args", help="additional arguments for the container runtime")
    parser.add_argument("path", metavar="PATH", default=".",
                        help="the path of the project")


def run(options):
    if options.path == ".":
        project_path = os.getcwd()
    else:
        project_path = os.path.abspath(options.path)
    path = Path(project_path)
    if path.exists() and not path.is_dir():
        log.error(f"Project path {path} exists and is not a directory.")
    project = Project.from_toml(path)
    source = ConfigSource.load_all(project_path=path)
    fragments = []
    for frag in options.fragments:
        try:
            p = Path(frag).resolve(strict=True)
        except OSError as err:
            log.error(f"Unable to resolve fragment {frag}: {err}")
        fragments.append(p)
    log.info(f"Fragments: {fragments}")
    return build_project(project, source, fragments, options.runtime_args)
