# SPDX-FileCopyrightText: 2026  Igalia S.L.
# SPDX-License-Identifier: MIT

import os
import subprocess

from enum import Enum
from pathlib import Path

from . import log, utils
from .config import ConfigSource
from .project import Project


class ContainerCommand(Enum):
    BUILD = "build"
    SHELL = "shell"

    def __str__(self):
        return self.name.lower()


def setup_container(
    project: Project,
    source: ConfigSource,
    command: ContainerCommand,
    interactive: bool = False,
    writable: bool = False,
    work_dir: Path | None = None,
    fragments: list[Path] = [],
    runtime_args: str | None = None,
) -> int:
    log.debug(f"Container engine: {source['container.engine']}")

    kas_file = f"{project.name}-image-base-{project.machine.name}.yml"
    log.debug(f"KAS file: {kas_file}")

    container_image = f"{source['container.image_path']}/{source['container.image_name']}:{source['container.image_version']}"
    log.debug(f"KAS container image: {container_image}")

    sstate_dir = project.safe_path_replace(source["build.sstate_dir"])
    log.debug(f"SSTATE_DIR = {sstate_dir}")
    dl_dir = project.safe_path_replace(source["build.download_dir"])
    log.debug(f"DL_DIR = {dl_dir}")

    if work_dir is None:
        work_dir = Path(os.getcwd())

    build_dir = work_dir / "build"
    try:
        build_dir.mkdir(parents=True, exist_ok=True)
        gitignore = build_dir / ".gitignore"
        with gitignore.open(mode="w") as f:
            f.write("# This file is autogenerated by moonforge; any change will be ignored when the directory is recreated.")
            f.write("*\n")
    except Exception as err:
        log.error(f"Unable to create build directory: {err}")

    try:
        sstate_dir.mkdir(parents=True, exist_ok=True)
        dl_dir.mkdir(parents=True, exist_ok=True)
    except Exception as err:
        log.error(f"Unable to create cache directories: {err}")

    if writable:
        repo_access = "rw"
    else:
        repo_access = "ro"

    engine = utils.find_program(source["container.engine"], error_if_not_found=True)
    assert engine is not None

    cmdline = [engine, "run"]

    cmdline.extend([
        "-v", f"{project.path}:/repo:{repo_access}",
        "-v", f"{work_dir}:/work:rw",
        "-v", f"{build_dir}:/build:rw",
        "-v", f"{dl_dir}:/downloads:rw",
        "-v", f"{sstate_dir}:/sstate:rw",
        "--workdir=/repo",
        "-e", "KAS_WORK_DIR=/work",
        "-e", "KAS_BUILD_DIR=/build",
        "-e", "DL_DIR=/downloads",
        "-e", "SSTATE_DIR=/sstate",
        "-e", f"USER_ID={os.getuid()}",
        "-e", f"GROUP_ID={os.getgid()}",
        "--rm",
        "--init",
    ])

    if interactive:
        cmdline.extend(["-t", "-i"])

    kas_env = {
        "TERM": os.environ.get("TERM"),
        "KAS_DISTRO": os.environ.get("KAS_DISTRO"),
        "KAS_MACHINE": os.environ.get("KAS_MACHINE"),
        "KAS_TARGET": os.environ.get("KAS_TARGET"),
        "KAS_TASK": os.environ.get("KAS_TASK"),
        "KAS_CLONE_DEPTH": os.environ.get("KAS_CLONE_DEPTH"),
        "KAS_PREMIRRORS": os.environ.get("KAS_PREMIRRORS"),
        "DISTRO_APT_PREMIRRORS": os.environ.get("DISTRO_APT_PREMIRRORS"),
        "BB_NUMBER_THREADS": os.environ.get("BB_NUMBER_THREADS"),
        "PARALLEL_MAKE": os.environ.get("PARALLEL_MAKE"),
        "GIT_CREDENTIAL_USEHTTPPATH": os.environ.get("GIT_CREDENTIAL_USEHTTPPATH"),
    }

    for var in kas_env:
        if kas_env[var] is not None:
            cmdline.append(f'-e {var}="{kas_env[var]}"')

    shell = os.environ.get("SHELL")
    match shell:
        case "/bin/sh" | "/bin/bash" | "/bin/dash":
            cmdline.append(f"-e SHELL={shell}")
        case _:
            cmdline.append("-e SHELL=/bin/bash")

    cmdline.extend([
        "--log-driver=none",
        "--user=root",
    ])

    if source["container.engine"] == "podman":
        cmdline.extend([
            "--security-opt", "label=disable",
            "--userns=keep-id",
        ])

    if runtime_args is not None:
        cmdline.append(runtime_args)

    cmdline.append(container_image)

    # All fragment paths are normalized and resolved to ensure that they
    # exist before creating the execution environment; now we have to
    # normalize them again against the volume exposed in the container
    project_basedir = project.path.name
    fragment_files = [str(Path("/repo/kas") / kas_file)]
    for kf in fragments:
        idx = kf.parts.index(project_basedir)
        fragment_files.append(str(Path("/repo").joinpath(*kf.parts[idx + 1:])))

    kas_files = ":".join(fragment_files)
    cmdline.extend([str(command), kas_files])

    log.debug(f"cmdline: {' '.join(cmdline)}")

    try:
        proc = subprocess.run(cmdline)
    except Exception as err:
        log.error(f"Unable to run {command} for project: {err}")

    return proc.returncode
