name: Python Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 1

    - name: "Set up Python"
      uses: actions/setup-python@v6
      with:
        python-version-file: "pyproject.toml"
        cache: "pip"
    - run: |
        pip install poetry
        poetry install --with lint

    - name: Flake8
      run: |
        poetry run flake8

    - name: MyPy
      run: |
        poetry run mypy src
